const express = require('express')
let usercontroller = require('../controller/usercontroller.js')
const validateuser = require('../middleware/validateduser.js')
 const router = express.Router()
 router.route('/user/Register')
 .post(validateuser(),usercontroller.adduser)
 router.route('/user/update/:id')
 .patch(validateuser(),usercontroller.updateuser)
 router.route('/user/restpawword')
 .post(usercontroller.restPasswordCode)
 router.route('/user/login')
 .post(usercontroller.userlogin)
 router.route('/user/newpassword').post(usercontroller.restPasswordvild)
 module.exports=router